set MATLAB=C:\PROGRA~1\MATLAB\R2018b
"%MINGW_DIR%\bin\sh.exe" --login -c "cd \"%CD%\" && make -f Template_Simulink_Model_QuanserDCMotor.mk  MAT_FILE=0 DEBUG=0 DEBUG_HEAP=0 COMBINE_OUTPUT_UPDATE_FCNS=0 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DEXT_MODE -DON_TARGET_WAIT_FOR_START=0""
